services:
  app:
    image: ghcr.io/timsu92/bun_template:main
    environment:
      - PROJECT_PATH=/project
      - TZ=Asia/Taipei
    volumes:
      - ..:/project:rw,cached
      - ${BUN_INSTALL_CACHE_DIR:-${HOME}/.bun/install/cache}:/root/.bun/install/cache:rw,z
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities: [gpu]

# secrets:
#   GITHUB_TOKEN:
#     environment: GITHUB_TOKEN
